######################## default configuration ####################
baseURL = "http://example.org/"
languageCode = "ca-ES"
title = "Frankfurt Tirol"
theme = "restaurant-hugo"
summaryLength = "10"
paginate = 4

############################# Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
URL = "css/bootstrap.min.css"
[[params.plugins.css]]
URL = "css/slick.css"
[[params.plugins.css]]
URL = "css/font-awesome.min.css"
[[params.plugins.css]]
URL = "css/animate.min.css"
[[params.plugins.css]]
URL = "css/venobox.css"
[[params.plugins.css]]
URL = "css/main.css"
[[params.plugins.css]]
URL = "css/responsive.css"

# JS Plugins
[[params.plugins.js]]
URL = "js/jquery.min.js"
[[params.plugins.js]]
URL = "js/bootstrap.min.js"
[[params.plugins.js]]
URL = "js/slick.min.js"
[[params.plugins.js]]
URL = "js/wow.min.js"
[[params.plugins.js]]
URL = "js/venobox.min.js"
[[params.plugins.js]]
URL = "js/main.js"

############################## navigation ###############################

[[menu.main]]
name = "Inici"
URL = "hero-area"
weight = 1

[[menu.main]]
name = "sobre Nosaltres"
URL = "about-us"
weight = 2

[[menu.main]]
name = "Nostra Carta"
URL = "price"
weight = 3

[[menu.main]]
name = "Contacte"
URL = "contact-us"
weight = 4

[[menu.main]]
name = "Blog"
URL = "blog"
weight = 5

[[menu.main]]
name = "News"
URL = "subscribe"
weight = 6


#################### default parameters ################################
[params]
logo = "images/logo_titulo.png" #logo = "images/logo.png"
# meta data
author = "Themefisher"
description = "This is meta description"
# google analitycs ID
google_analitycs_id = "Your ID"
# mainSections
main_sections = ["post"]
# copyright
copyright = "Copyright &copy; 2020 Designed by [Themefisher](https://themefisher.com) & Developed by [Gethugothemes](https://gethugothemes.com)"

# Preloader
[params.preloader]
enable = false
preloader = "" # use .png , .svg or .gif format

################################### Footer ############################
[params.footer]
enable = true
contactInfoTitle = "CONTACE E <span>INFO</span> "
blogTitle = "DARRERS <span>BLOG POSTS</span>"
galleryTitle = "IMATGES <span>STREAM</span>"
socialTitle = "SEGEIX-<span>NOS</span>"

############################ footer contact item
[[params.footer.contactItem]]
title="Telèfon"
icon = "fa fa-phone"
content = "+34 937 80 49 28"

[[params.footer.contactItem]]
title="adreça"
icon = "fa fa-map-marker"
content = "2046 Blue Spruce Lane Laurel Canada"

[[params.footer.contactItem]]
title="E mail"
icon = "fa fa-envelope"
content = "info@franfurt-tirol.com"

######################### footer gallery
[[params.footer.gallery]]
image = "images/slider/adobado_con_guarnicion.jpg"

[[params.footer.gallery]]
image = "images/slider/atun-huevo-piminientos.jpeg"

[[params.footer.gallery]]
image =  "images/slider/huevo-anchoa-pimientos.jpeg"

[[params.footer.gallery]]
image = "images/slider/huevos-aptatas-bacon.jpeg"

[[params.footer.gallery]]
image = "images/slider/sepia_ensladilla.jpg"

[[params.footer.gallery]]
image = "images/slider/slider-img-3.jpg"

[[params.footer.gallery]]
image = "images/slider/tortilla-butiffarra-ensalda.jpeg"


######################## Social Icon 
[[params.footer.socialLink]]
icon = "facebook"
link = "https://fb.com/themefisher"

[[params.footer.socialLink]]
icon = "twitter"
link = "https://fb.com/themefisher"

[[params.footer.socialLink]]
icon = "dribbble"
link = "https://fb.com/themefisher"

[[params.footer.socialLink]]
icon = "instagram"
link = "https://fb.com/themefisher"